import React,{useEffect,useMemo,useRef,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
type Song={id:string;title:string;artist:string;album:string;blob:Blob;favorite:boolean;lastPlayed?:number};type Playlist={id:string;name:string;songIds:string[]};type Tab='home'|'search'|'library'|'playlists'|'profile';
const DB='gamewave-v1',id=()=>crypto.randomUUID(),fmt=(n:number)=>`${Math.floor(n/60)}:${Math.floor(n%60).toString().padStart(2,'0')}`;
function store(name:string){return new Promise<IDBObjectStore>((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{for(const s of ['songs','playlists','settings'])if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:s==='settings'?'key':'id'})};r.onsuccess=()=>resolve(r.result.transaction(name,'readwrite').objectStore(name));r.onerror=()=>reject(r.error)})}
async function all<T>(name:string){const s=await store(name);return new Promise<T[]>(res=>{const r=s.getAll();r.onsuccess=()=>res(r.result)})}async function put(name:string,v:any){const s=await store(name);return new Promise<void>(res=>{s.put(v).onsuccess=()=>res()})}async function del(name:string,k:string){const s=await store(name);return new Promise<void>(res=>{s.delete(k).onsuccess=()=>res()})}
const Icon=({n}:{n:string})=><span className="ico">{({home:'⌂',search:'⌕',music:'♫',list:'☷',user:'◯',plus:'＋',play:'▶',pause:'Ⅱ',next:'▶|',prev:'|◀',heart:'♥',shuffle:'⤨',repeat:'↻',trash:'⌫',back:'‹',edit:'✎'}as any)[n]||'•'}</span>;
function Cover({blob,big=false}:{blob?:Blob,big?:boolean}){const[u,setU]=useState('');useEffect(()=>{if(!blob){setU('');return}const x=URL.createObjectURL(blob);setU(x);return()=>URL.revokeObjectURL(x)},[blob]);return <div className={'cover '+(big?'big':'')}>{u?<img src={u}/>:<span>♫</span>}</div>}
export default function App(){const[a,setA]=useState<Song[]>([]),[p,setP]=useState<Playlist[]>([]),[tab,setTab]=useState<Tab>('home'),[q,setQ]=useState(''),[cur,setCur]=useState<Song>(),[queue,setQueue]=useState<Song[]>([]),[qi,setQi]=useState(0),[playing,setPlaying]=useState(false),[pos,setPos]=useState(0),[dur,setDur]=useState(0),[shuffle,setShuffle]=useState(false),[repeat,setRepeat]=useState(false),[full,setFull]=useState(false),[toast,setToast]=useState('');const audio=useRef<HTMLAudioElement>();const file=useRef<HTMLInputElement>(null);
useEffect(()=>{Promise.all([all<Song>('songs'),all<Playlist>('playlists')]).then(([x,y])=>{setA(x);setP(y)})},[]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)},[toast]);
const save=async(s:Song)=>{await put('songs',s);setA(await all<Song>('songs'))};
const play=(s:Song,list=a)=>{const i=Math.max(0,list.findIndex(x=>x.id===s.id));setQueue(list);setQi(i);setCur(list[i]);save({...s,lastPlayed:Date.now()})};
useEffect(()=>{if(!cur)return;audio.current?.pause();const x=new Audio(URL.createObjectURL(cur.blob));audio.current=x;x.onloadedmetadata=()=>setDur(x.duration||0);x.ontimeupdate=()=>setPos(x.currentTime);x.onplay=()=>setPlaying(true);x.onpause=()=>setPlaying(false);x.onended=()=>next();x.play().catch(()=>{});return()=>{x.pause();URL.revokeObjectURL(x.src)}},[cur]);
const next=()=>{if(!queue.length)return;let n=qi+1;if(shuffle&&queue.length>1)do n=Math.floor(Math.random()*queue.length);while(n===qi);if(n>=queue.length){if(!repeat)return;n=0}setQi(n);setCur(queue[n])};const prev=()=>{if(!audio.current)return;if(pos>3){audio.current.currentTime=0;return}let n=qi-1;if(n<0){if(!repeat)return;n=queue.length-1}setQi(n);setCur(queue[n])};
const importMusic=async(fs:FileList|null)=>{if(!fs)return;let n=0;for(const f of Array.from(fs)){if(!f.type.startsWith('audio/')&&!/\.(mp3|m4a|aac|wav|flac|ogg|opus)$/i.test(f.name))continue;await put('songs',{id:id(),title:f.name.replace(/\.[^.]+$/,''),artist:'Unknown Artist',album:'Local Music',blob:f,favorite:false});n++}setA(await all<Song>('songs'));setToast(`${n} lagu ditambahkan.`)};
const fav=async(s:Song)=>save({...s,favorite:!s.favorite});const remove=async(s:Song)=>{if(!confirm(`Hapus "${s.title}"?`))return;await del('songs',s.id);setA(await all<Song>('songs'));if(cur?.id===s.id){audio.current?.pause();setCur(undefined);setFull(false)}};
const create=async()=>{const name=prompt('Nama playlist:');if(!name)return;await put('playlists',{id:id(),name,songIds:[]});setP(await all<Playlist>('playlists'))};const add=async(s:Song)=>{if(!p.length){setToast('Buat playlist terlebih dahulu.');return}const n=prompt('Nomor playlist:\n'+p.map((x,i)=>`${i+1}. ${x.name}`).join('\n'));const x=p[Number(n)-1];if(!x)return;await put('playlists',{...x,songIds:x.songIds.includes(s.id)?x.songIds:[...x.songIds,s.id]});setP(await all<Playlist>('playlists'));setToast('Ditambahkan ke playlist.')};
const filtered=useMemo(()=>a.filter(s=>(s.title+' '+s.artist+' '+s.album).toLowerCase().includes(q.toLowerCase())),[a,q]);const recent=[...a].filter(s=>s.lastPlayed).sort((x,y)=>(y.lastPlayed||0)-(x.lastPlayed||0)).slice(0,6);const favs=a.filter(x=>x.favorite);
return <div className="app"><header><div className="brand"><b>GW</b><span>GAMEWAVE<small>MUSIC</small></span></div><button onClick={()=>file.current?.click()}><Icon n="plus"/></button><input ref={file} hidden type="file" multiple accept="audio/*,.flac,.wav" onChange={e=>importMusic(e.target.files)}/></header><main>
{tab==='home'&&<><div className="welcome"><div><small>YOUR PERSONAL SOUNDTRACK</small><h1>Good evening.</h1><p>Local music player dengan gaya gaming premium.</p></div><button className="primary" onClick={()=>file.current?.click()}><Icon n="plus"/> Add Music</button></div>{(recent[0]||a[0])?<div className="hero" onClick={()=>{play(recent[0]||a[0]);setFull(true)}}><Cover blob={(recent[0]||a[0]).blob} big/><div><small>CONTINUE LISTENING</small><h2>{(recent[0]||a[0]).title}</h2><p>{(recent[0]||a[0]).artist}</p><button className="round"><Icon n="play"/></button></div></div>:<div className="empty"><h2>Library masih kosong</h2><p>Import musik dari HP. File disimpan lokal di browser.</p><button className="primary" onClick={()=>file.current?.click()}>Import Music</button></div>}<h2 className="sect">Quick Access</h2><div className="quick"><button onClick={()=>favs[0]&&play(favs[0],favs)}><b>♥ Favorites</b><small>{favs.length} tracks</small></button><button onClick={()=>a[0]&&play(a[0],a)}><b>♫ All Music</b><small>{a.length} tracks</small></button></div>{recent.length>0&&<><h2 className="sect">Recently Played</h2><Rows list={recent} play={play}/></>}</>}
{tab==='search'&&<><div className="search"><Icon n="search"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title, artist, album..."/></div><Rows list={filtered} play={play} fav={fav} add={add} remove={remove}/></>}
{tab==='library'&&<><div className="title"><div><small>LOCAL LIBRARY</small><h1>My Music</h1><p>{a.length} tracks</p></div><button className="primary" onClick={()=>file.current?.click()}>＋ Add Music</button></div>{a.length?<Rows list={a} play={play} fav={fav} add={add} remove={remove}/>:<div className="empty"><h2>No tracks yet</h2><button className="primary" onClick={()=>file.current?.click()}>Add your first song</button></div>}</>}
{tab==='playlists'&&<Playlists ps={p} songs={a} create={create} play={play} setP={setP}/>} {tab==='profile'&&<Profile songs={a} ps={p}/>}</main>
{cur&&<div className="mini"><button onClick={()=>setFull(true)}><Cover blob={cur.blob}/></button><div onClick={()=>setFull(true)}><b>{cur.title}</b><small>{cur.artist}</small></div><button onClick={()=>playing?audio.current?.pause():audio.current?.play()}><Icon n={playing?'pause':'play'}/></button><button onClick={next}><Icon n="next"/></button><i><span style={{width:`${dur?pos/dur*100:0}%`}}/></i></div>}
<nav>{([['home','Home'],['search','Search'],['library','Library'],['playlists','Playlists'],['profile','Profile']] as const).map(([x,t])=><button className={tab===x?'on':''} onClick={()=>setTab(x)} key={x}><Icon n={x==='home'?'home':x==='search'?'search':x==='library'?'music':x==='playlists'?'list':'user'}/><span>{t}</span></button>)}</nav>{full&&cur&&<div className="player"><button className="back" onClick={()=>setFull(false)}>‹ NOW PLAYING</button><Cover blob={cur.blob} big/><small>GAMEWAVE LOCAL</small><h1>{cur.title}</h1><p>{cur.artist}</p><button className={cur.favorite?'heart liked':'heart'} onClick={()=>fav(cur)}>♥</button><input type="range" min="0" max={dur||1} step=".1" value={Math.min(pos,dur||1)} onChange={e=>{if(audio.current)audio.current.currentTime=+e.target.value}}/><div className="times"><span>{fmt(pos)}</span><span>{fmt(dur)}</span></div><div className="controls"><button className={shuffle?'on':''} onClick={()=>setShuffle(!shuffle)}>⤨</button><button onClick={prev}>|◀</button><button className="bigplay" onClick={()=>playing?audio.current?.pause():audio.current?.play()}>{playing?'Ⅱ':'▶'}</button><button onClick={next}>▶|</button><button className={repeat?'on':''} onClick={()=>setRepeat(!repeat)}>↻</button></div></div>}{toast&&<div className="toast">{toast}</div>}</div>}
function Rows({list,play,fav,add,remove}:{list:Song[],play:(s:Song,l?:Song[])=>void,fav?:(s:Song)=>void,add?:(s:Song)=>void,remove?:(s:Song)=>void}){return list.length?<div className="rows">{list.map(s=><div className="row" key={s.id}><button className="coverbtn" onClick={()=>play(s,list)}><Cover blob={s.blob}/></button><button className="song" onClick={()=>play(s,list)}><b>{s.title}</b><small>{s.artist} · {s.album}</small></button>{fav&&<button onClick={()=>fav(s)} className={s.favorite?'liked':''}>♥</button>}{add&&<button onClick={()=>add(s)}>＋</button>}{remove&&<button onClick={()=>remove(s)}>⌫</button>}</div>)}</div>:<div className="empty"><h3>No music found</h3></div>}
function Playlists({ps,songs,create,play,setP}:{ps:Playlist[],songs:Song[],create:()=>void,play:(s:Song[],l?:Song[])=>void,setP:(x:Playlist[])=>void}){const[selected,setSelected]=useState<Playlist>();if(selected){const ss=songs.filter(s=>selected.songIds.includes(s.id));return <><button className="backlink" onClick={()=>setSelected(undefined)}>‹ Playlists</button><div className="playlistHead"><div className="playlistArt">♫</div><div><small>PLAYLIST</small><h1>{selected.name}</h1><p>{ss.length} tracks</p><button className="primary" onClick={()=>play(ss)}>▶ Play All</button></div></div><Rows list={ss} play={play}/></>}return <><div className="title"><div><small>YOUR COLLECTIONS</small><h1>Playlists</h1><p>{ps.length} playlists</p></div><button className="primary" onClick={create}>＋ New Playlist</button></div>{ps.length?<div className="grid">{ps.map(x=><button className="pcard" key={x.id} onClick={()=>setSelected(x)}><div>♫</div><b>{x.name}</b><small>{x.songIds.length} tracks</small></button>)}</div>:<div className="empty"><h2>Create your first playlist</h2><button className="primary" onClick={create}>＋ New Playlist</button></div>}</>}
function Profile({songs,ps}:{songs:Song[],ps:Playlist[]}){return <><div className="profile"><div className="avatar">G</div><small>PROFILE</small><h1>GAMEWAVE User</h1><p>@gamewave · Music, games & good vibes.</p></div><div className="stats"><div><b>{songs.length}</b><small>Tracks</small></div><div><b>{ps.length}</b><small>Playlists</small></div><div><b>{songs.filter(s=>s.favorite).length}</b><small>Favorites</small></div></div><div className="note"><b>Local-first storage</b><p>Musik yang di-import disimpan di IndexedDB browser. Netlify hanya meng-host aplikasi.</p></div></>}
